# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2934dcf79192ec241257fef6749a4417959e13185d11be4736aa61b0bea5b90bba9e37d6878fe949878e61347178074d030419b0ce5b6b18719599e7689d084e

test:
  secret_key_base: 5569ecdc94380a84a62b218785825044c5dfda69ed909bea6a90bd4189cf9f1e4f51a794fbf3630e4d7eea6ddc38c9872fa45a4983748250926064c833b84322

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
